# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import qrcode_pb2 as qrcode__pb2


class QrgeneraterStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QrCode = channel.unary_unary(
                '/qrcode.Qrgenerater/QrCode',
                request_serializer=qrcode__pb2.QrRequest.SerializeToString,
                response_deserializer=qrcode__pb2.QrReply.FromString,
                )


class QrgeneraterServicer(object):
    """The greeting service definition.
    """

    def QrCode(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QrgeneraterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QrCode': grpc.unary_unary_rpc_method_handler(
                    servicer.QrCode,
                    request_deserializer=qrcode__pb2.QrRequest.FromString,
                    response_serializer=qrcode__pb2.QrReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qrcode.Qrgenerater', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Qrgenerater(object):
    """The greeting service definition.
    """

    @staticmethod
    def QrCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qrcode.Qrgenerater/QrCode',
            qrcode__pb2.QrRequest.SerializeToString,
            qrcode__pb2.QrReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
