version: "3.8"
services:
  app:
    build: .
    ports:  
      - "5001:5000"
    container_name: app
    volumes:
      - ./app:/usr/src/app
    
  

  mysql:
    ports:
      - 3307:3306
    container_name: myDB
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: Ikuma0219!
      MYSQL_DATABASE: myDB
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/db/data:/var/lib/mysql
    