# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qrcode.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cqrcode.proto\x12\x06qrcode\"\x19\n\tQrRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1a\n\x07QrReply\x12\x0f\n\x07message\x18\x01 \x01(\t2t\n\tGenerator\x12\x33\n\x0bQrGenerator\x12\x11.qrcode.QrRequest\x1a\x0f.qrcode.QrReply\"\x00\x12\x32\n\nGetkeiretu\x12\x11.qrcode.QrRequest\x1a\x0f.qrcode.QrReply\"\x00\x42.\n\x17io.grpc.examples.qrcodeB\x0bQrcodeProtoP\x01\xa2\x02\x03QRCb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qrcode_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027io.grpc.examples.qrcodeB\013QrcodeProtoP\001\242\002\003QRC'
  _QRREQUEST._serialized_start=24
  _QRREQUEST._serialized_end=49
  _QRREPLY._serialized_start=51
  _QRREPLY._serialized_end=77
  _GENERATOR._serialized_start=79
  _GENERATOR._serialized_end=195
# @@protoc_insertion_point(module_scope)
