# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import qrcode_pb2 as qrcode__pb2


class GeneratorStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QrGenerator = channel.unary_unary(
                '/qrcode.Generator/QrGenerator',
                request_serializer=qrcode__pb2.QrRequest.SerializeToString,
                response_deserializer=qrcode__pb2.QrReply.FromString,
                )
        self.Getkeiretu = channel.unary_unary(
                '/qrcode.Generator/Getkeiretu',
                request_serializer=qrcode__pb2.QrRequest.SerializeToString,
                response_deserializer=qrcode__pb2.QrReply.FromString,
                )
        self.Getotp = channel.unary_unary(
                '/qrcode.Generator/Getotp',
                request_serializer=qrcode__pb2.QrRequest.SerializeToString,
                response_deserializer=qrcode__pb2.QrReply.FromString,
                )


class GeneratorServicer(object):
    """The greeting service definition.
    """

    def QrGenerator(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Getkeiretu(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Getotp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GeneratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QrGenerator': grpc.unary_unary_rpc_method_handler(
                    servicer.QrGenerator,
                    request_deserializer=qrcode__pb2.QrRequest.FromString,
                    response_serializer=qrcode__pb2.QrReply.SerializeToString,
            ),
            'Getkeiretu': grpc.unary_unary_rpc_method_handler(
                    servicer.Getkeiretu,
                    request_deserializer=qrcode__pb2.QrRequest.FromString,
                    response_serializer=qrcode__pb2.QrReply.SerializeToString,
            ),
            'Getotp': grpc.unary_unary_rpc_method_handler(
                    servicer.Getotp,
                    request_deserializer=qrcode__pb2.QrRequest.FromString,
                    response_serializer=qrcode__pb2.QrReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qrcode.Generator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Generator(object):
    """The greeting service definition.
    """

    @staticmethod
    def QrGenerator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qrcode.Generator/QrGenerator',
            qrcode__pb2.QrRequest.SerializeToString,
            qrcode__pb2.QrReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Getkeiretu(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qrcode.Generator/Getkeiretu',
            qrcode__pb2.QrRequest.SerializeToString,
            qrcode__pb2.QrReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Getotp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qrcode.Generator/Getotp',
            qrcode__pb2.QrRequest.SerializeToString,
            qrcode__pb2.QrReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
